### ISSUE TITLE
a sku can be used to identify a Product Variant when updating a Product

### ISSUE THREAD

**Issue by schleichardt** [commercetools/commercetools-jvm-sdk#1023]
see  Release Notes - commercetools™ platform - Version Release 23.09.2015 https://dev.commercetools.com/release-notes.html#release-2015-09-23

* [ ] add badge

**Comment by mht-dotsource** [comment]
@schleichardt just to be sure. Am I right to assume following Product Updateactions needs to be adjusted that they take sku alternatively to the variantId?

- [ ] Remove ProductVariant
- [ ] Change Master Variant
- [ ] Add Price
- [ ] Set Prices
- [ ] Set Attribute
- [ ] Add External Image
- [ ] Move Image To Position
- [ ] Remove Image

**Comment by mht-dotsource** [comment]
@schleichardt additional question. now with the option to create the updateactions with sku instead of variant the getId() method becomes nullable. is that considered to be breaking backward compatibility?

**Comment by schleichardt** [comment]
Looks good, I think "Move Image To Position" is not implemented yet, so I you can do this in this pull request or a next or tell me that you don't want to add it. As you prefer.

Yes, the getter for the variantId and the fields need to be annotated with `@Nullable`. I will mention the "breaking change" in the release notes.

**Comment by yanns** [comment]
You should stay backwards compatible.
My suggestion:

- add the methods `ofVariantId` and `ofSku`
- change the implementation of `of` to simply call `ofVariantId`

What do you think of this?

**Comment by ccsalazarr-commercetools** [comment]
That was what I thought, but I wanted to be sure :thumbsup:
