### ISSUE TITLE
state search filter

### ISSUE THREAD

**Issue by schleichardt** [commercetools/commercetools-jvm-sdk#1031]
http://localhost:4004/release-notes.html#release-2016-01-12

**Comment by katmatt** [comment]
Documentation for this feature is now available at http://dev.commercetools.com/http-api-projects-products-search.html#filter-by-state.

**Comment by katmatt** [comment]
Looks like it's already implemented:
https://github.com/commercetools/commercetools-jvm-sdk/blob/dd540446a4a9a59fe2760b96ed4cc7f0fe0c4aee/commercetools-models/src/main/java/io/sphere/sdk/products/search/ProductProjectionFilterSearchModel.java#L66

And we have an integration test too:
https://github.com/commercetools/commercetools-jvm-sdk/blob/b3768bec927e9d38c500e7e57198cc53faf7dc81/commercetools-models/src/test/java/io/sphere/sdk/products/search/ExistsAndMissingFilterIntegrationTest.java#L71

**Comment by katmatt** [comment]
@lauraluiz Do you agree that we can close this issue because it's already fixed? Or did I miss something? 

And if we close this issue, I think we have to add a badge to our release notes?

**Comment by lauraluiz** [comment]
@katmatt yes, let's close it. I understand Michael's comment as the indication that it was already in the 1.7.0 milestone but it was not released when he wrote it.
And yes, the badge is missing. Can you try and add it?

**Comment by katmatt** [comment]
@lauraluiz Ok, I will do that and open a PR. But to me it looks like we shipped this with 1.0.0-RC4?
