### ISSUE TITLE
check again product classes for missing fields

### ISSUE THREAD

**Issue by schleichardt** [commercetools/commercetools-jvm-sdk#1056]
- product projection state field is missing

**Comment by schleichardt** [comment]
state field has been added in https://github.com/sphereio/sphere-jvm-sdk/pull/1067

**Comment by ccsalazarr-commercetools** [comment]
@katmatt I have checked the implementation classes of Product, ProductCatalogData, ProductData, ProductVariant, ProductVariantAvailability, ProductDraft, ProductVariantDraft and ProductProjection, and they all have complete the fields.

**Comment by katmatt** [comment]
Thanks a lot and then I will close this issue 👍
