### ISSUE TITLE
check if scopedPrices support missing and exists filter?

### ISSUE THREAD

**Issue by schleichardt** [commercetools/commercetools-jvm-sdk#1107]

**Comment by schleichardt** [comment]
@gogregor Can I use the exists and missing filters for the scoped prices?

**Comment by gogregor** [comment]
@OlegIlyenko what do you think, should we officially support this?

**Comment by OlegIlyenko** [comment]
I think it should work even now, we need to check it. In general I think we can officially support this for scoped prices

**Comment by gogregor** [comment]
Yes, I also expect it to work. Just wanted to check that it will not bite us in the future with all those special price logic.

**Comment by katmatt** [comment]
We used the exists filter on the scoped price successfully, this means that it's already implemented and works fine. Looks like we forgot to close this issue.
