### ISSUE TITLE
evaluate generating the correlation ID on the client side

### ISSUE THREAD

**Issue by schleichardt** [commercetools/commercetools-jvm-sdk#1131]

**Comment by schleichardt** [comment]
workarounds:

for all requests: manipulate the HttpRequestIntent in execute of http://commercetools.github.io/commercetools-jvm-sdk/apidocs/io/sphere/sdk/client/SphereClientDecorator.html

for single requests: manipulate the HttpRequestIntent in http://commercetools.github.io/commercetools-jvm-sdk/apidocs/io/sphere/sdk/client/SphereRequestDecorator.html

**Comment by schleichardt** [comment]
the header name: `X-Correlation-ID`

**Comment by schleichardt** [comment]
Here is a workaround example: https://gist.github.com/schleichardt/f2c3fe8c2d820f88240db372e449944b#file-correlationidsphereclient-java

**Comment by katmatt** [comment]
Duplicates #1491
