### ISSUE TITLE
Add new option flag for recalculate update action of a cart

### ISSUE THREAD

**Issue by mmoelli** [commercetools/commercetools-jvm-sdk#1152]
http://dev.commercetools.com/release-notes.html#release-notes---commercetools-platform---version-release-09062016

**Comment by trangng** [comment]
@schleichardt when will this be available in the sdk?

**Comment by schleichardt** [comment]
don't know, currently I am fully busy with Sunrise Framework checkout, but it could be added via a pull request from a developer.

**Comment by trangng** [comment]
@salander or @butenkor can one of you do it?

**Comment by salander** [comment]
as we need it for merkur, i will do it asap.
