### ISSUE TITLE
add ProductProjectionSearch.ofCurrent().bySlug(locale, slug)

### ISSUE THREAD

**Issue by schleichardt** [commercetools/commercetools-jvm-sdk#1156]

**Comment by mht-dotsource** [comment]
@schleichardt the other methods follow the naming "with..." or "plus..." e.g. withPriceSelection() should i follow the naming convention or is the bySlug somehow different?

**Comment by schleichardt** [comment]
it is just to this io.sphere.sdk.products.queries.ProductProjectionQuery#bySlug for the search endpoint.

I wouldn't mind if you also provide bySku as in query.
