### ISSUE TITLE
CategoryDraft and CategoryDraftBuilder lack meta fields

### ISSUE THREAD

**Issue by selo-ecube** [commercetools/commercetools-jvm-sdk#1179]
How shall we set metaTitle, metaDescription and metaKeywords in CategoryDraft that are documented in the [HTTP API](http://dev.commercetools.com/http-api-projects-categories.html#categorydraft)? These fields seem to be lacking in CategoryDraft and CategoryDraftBuilder.

This issue seems to be related to #915 .

**Comment by schleichardt** [comment]
Thanks for reporting, we will attempt to fix it today.

**Comment by selo-ecube** [comment]
Thanks for the prompt fix!

**Comment by schleichardt** [comment]
yeah, I forgot to mention that is also released https://github.com/commercetools/commercetools-jvm-sdk/releases/tag/v1.2.0

**Comment by selo-ecube** [comment]
No problem, I'm watching the repository so I got an e-mail when 1.2.0 was released.
