### ISSUE TITLE
Improve BigDecimal support for product attributes

### ISSUE THREAD

**Issue by OlegIlyenko** [commercetools/commercetools-jvm-sdk#1180]
We noticed, that in some places (either in query builder or in JSON deserialization) `BigDecimal` is not fully supported for `number` product attribute type. We wanted to save latitude/longitude in these attributes, but as a workaround we had to use `long` instead (which is fully supported). It would be also nice to have support for other, less precise, floating point numbers (like `Double`)

**Comment by lauraluiz** [comment]
In particular it was the CustomerQuery DSL for custom fields. You can get a custom field value with floating point value but you can't query for it. Of course it was still possible to do with a manual written predicate, but it misled us as we thought it was simply not supported.

**Comment by schleichardt** [comment]
@lauraluiz for search BigDecimal? we have http://commercetools.github.io/commercetools-jvm-sdk/apidocs/io/sphere/sdk/products/search/ProductAttributeFilterSearchModel.html#ofNumber-java.lang.String-

**Comment by schleichardt** [comment]
http://commercetools.github.io/commercetools-jvm-sdk/apidocs/io/sphere/sdk/types/queries/FieldsQueryModel.html needs a BigDecimal field?

**Comment by lauraluiz** [comment]
Precisely. As you see it has the `Long` field but not a `BigDecimal/Number` field.
