### ISSUE TITLE
PaymentTransactionStateChangedMessage is missing TransactionId

### ISSUE THREAD

**Issue by mht-dotsource** [commercetools/commercetools-jvm-sdk#1189]
The Messages from the CTP contains also the TransactionId. 

At the moment the JVM SDK PaymentTransactionStateChangeMessage Object does not contain this Id.

**Comment by schleichardt** [comment]
I don't see there a field for the transaction ID: http://dev.commercetools.com/http-api-projects-messages.html#paymenttransactionstatechanged-message

**Comment by mht-dotsource** [comment]
Yeah I don' t see it either :) . It's not in the documentation. Still it's in the answer of the Platform and also it's nessisary for the structure of the message.

Otherwise there is no way to be sure which transaction of the payment has changed.
@schleichardt: Can you talk with the core team if it's missing in the documentation or purposely not there.

**Comment by schleichardt** [comment]
reported

**Comment by schleichardt** [comment]
workaround:
http://commercetools.github.io/commercetools-jvm-sdk/apidocs/io/sphere/sdk/messages/Message.html#getPayload--

You can fetch for now the unmapped fields as JSON, but when I add the field to the class then it won't be anymore available anymore with this getter.

**Comment by cneijenhuis** [comment]
Sorry, my fault 😢

**Comment by schleichardt** [comment]
If everything goes well, we have tomorrow a release with a fix.

**Comment by mht-dotsource** [comment]
:+1:
