### ISSUE TITLE
Add ResourceIdentifier.ofSlug(...)

### ISSUE THREAD

**Issue by selo-ecube** [commercetools/commercetools-jvm-sdk#1191]
We use a multi-step process to import products into a Commercetools project via the JVM-SDK. Each import step is implemented in a separate class.

We use a step that creates ProductDraft and a separate later step that executes the CreateProductCommand for the ProductDraft. Only the last step shall access the Commercetools-HTTP-API. Therefore, in the step that creates the ProductDraft, we use ResourceIdentifier.ofKey(...) to refer to the ProductType of the ProductDraft.

We would like to do the same for the Category to be added to the ProductDraft. Unfortunately, Category does not have a key and ResourceIdentifier does have an ofSlug() method.

Could you add a ResourceIdentifier.ofSlug() method?

Please let me know if you need more info on this.

**Comment by schleichardt** [comment]
[ResourceIdentifier](https://dev.commercetools.com/http-api-types.html#resourceidentifier) is a platform object which is only with key or ID.

And in the platform assigning categories to a [ProductDraft](https://dev.commercetools.com/http-api-projects-products.html#productdraft) is only support by using category references (which is containing the ID).

In our import tools we fetch all categories in a [CategoryTree](http://commercetools.github.io/commercetools-jvm-sdk/apidocs/io/sphere/sdk/categories/CategoryTree.html) which has a finder method to get a category by slug. Categories have a [method](http://commercetools.github.io/commercetools-jvm-sdk/apidocs/io/sphere/sdk/categories/Category.html#toReference--) to get the reference.

So I can not add this method.
