### ISSUE TITLE
Documentation does not match header: Persistent objects vs. local test doubles

### ISSUE THREAD

**Issue by selo-ecube** [commercetools/commercetools-jvm-sdk#1192]
The file http://commercetools.github.io/commercetools-jvm-sdk/apidocs/io/sphere/sdk/meta/ConstructionDocumentation.html#persistent-objects has a heading _Persistent objects vs. local test doubles_ but what follows below the heading does not seem to include information on _local test doubles_.

**Comment by lauraluiz** [comment]
I think this probably comes like that from historical reasons, because before we had double test objects. Now only the persistent explanation remains. Will fix that, thanks!
