### ISSUE TITLE
InternalServerErrorException during multiple product update actions

### ISSUE THREAD

**Issue by fhaertig** [commercetools/commercetools-jvm-sdk#1207]
Hi,

occasionally I get a strange error response with the jvm sdk 1.3.0:

io.sphere.sdk.client.InternalServerErrorException: detailMessage: {
  "ehello":"I am a load balancer of api.sphere.io", "moreInfoAt":"http://status.commercetools.com",
  "ip":"5.79.36.218"
}

summary: POST https://api.sphere.io/***/products/4c06d757-cebd-4baf-bbda-49f99d7518af failed  with response code 500 on 2016-09-08T08:43:15.805Z
http response formatted body: {
  "ehello" : "I am a load balancer of api.sphere.io",
  "moreInfoAt" : "http://status.commercetools.com",
  "ip" : "5.79.36.218"
}
http response: io.sphere.sdk.http.HttpResponseImpl@7ac45ec2[statusCode=500,headers={Connection=[close], Date=[Thu, 08 Sep 2016 08:43:14 GMT], Content-Type=[text/html]},associatedRequest=<null>,textInterpretedBody={
  "ehello":"I am a load balancer of api.sphere.io", "moreInfoAt":"http://status.commercetools.com",
  "ip":"5.79.36.218"
}
]
SDK: 1.3.0

Followed by the json body of the command. This is happening during the execution of multiple product update and create commands in parallel. For each product, we create a separate thread from a thread pool, then determine the UpdateActions and send these by sphereClient.execute() to commercetools. It roughly looks like this:

```
productDrafts
                .stream()
                .map(draft -> CompletableFuture
                    .supplyAsync(() -> createProductCommandFromDraft(...), executor)
                    .thenCompose(this::executeCommandAsync)
                )
                .collect(Collectors.toList());

allOf(listOfFuturesToFutureOfList(completableFutures)).join();
```
Could someone elaborate on this?

**Comment by schleichardt** [comment]
It does not look like an SDK issue due to the 500er error and the load balancer appearing.

It could be the case that too much requests in parallel are started. 
You can control the maximum amount of parallel requests with http://commercetools.github.io/commercetools-jvm-sdk/apidocs/io/sphere/sdk/client/QueueSphereClientDecorator.html

If it does not help, consider to contact the commercetools support.

**Comment by fhaertig** [comment]
Sorry, indeed this is not really a problem with the sdk.
Thank you very much for pointing out the QueueSphereClientDecorator, didn't know about that!
