### ISSUE TITLE
Range validations raise exception due to lexicographic comparison

### ISSUE THREAD

**Issue by lauraluiz** [commercetools/commercetools-jvm-sdk#1247]
Filter/Facet Range<T> compares the bounds to decide whether the range is valid. Otherwise it would raise a `InvertedBoundsException`. The problem arises when numbers are passed as strings, which are compared in a lexicographic manner instead of numerically, thus raising an exception for inverted bounds where it is actually correct from the numerical perspective.

Passing numbers as strings is unavoidable, since in most cases the desired bounds are obtained as text (e.g. query string). Therefore either the exception is removed (and let the developer take responsibility of the validity of his range) or an additional layer of complexity is added to always receive the correct type, forcing the developer to previously convert the string to whatever object.

**Comment by lauraluiz** [comment]
@schleichardt I'm in favour of the 1st option, since the validation is unnecessary, the platform doesn't complain with it, it simply returns nothing. WDYT?

**Comment by schleichardt** [comment]
lets discuss this in a hangout

**Comment by schleichardt** [comment]
Fresh day, I also think it would be best to not throw the exception.

**Comment by schleichardt** [comment]
Can you do it? Otherwise assign the issue to me.

**Comment by lauraluiz** [comment]
Yep, will do it!
