### ISSUE TITLE
TaxCategoryQuery is throwing a JsonMappingException

### ISSUE THREAD

**Issue by fhaertig** [commercetools/commercetools-jvm-sdk#1257]
Hi, 

I'm trying to query for a TaxCategory with the sdk v.1.6.0 by using the following code:

 `final TaxCategoryQuery taxCategoryQuery = TaxCategoryQueryBuilder`
 `           .of()`
 `          .build();`
 `final PagedQueryResult<TaxCategory> queryResult = sphereClient.executeBlocking(taxCategoryQuery);`

The project can have zero or n TaxCategories, the outcome is always a JsonMappingException:

com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.lang.String out of START_OBJECT token
 at [Source: [B@56c4278e; line: 8, column: 19] (through reference chain: io.sphere.sdk.queries.PagedQueryResultImpl["results"]->java.util.ArrayList[0]->io.sphere.sdk.taxcategories.TaxCategoryImpl["name"])
http response: <unknown>
SDK: 1.6.0
project: <unknown>
Java: 1.8.0_92
cwd: /Users/<...>
sphere request: <unknown>
additional notes: [Cannot parse {
  "offset": 0,
  "count": 1,
  "total": 1,
  "results": [
    {
      "id": "f563e2b1-a592-4f2f-af09-791cd336fb8d",
      "version": 1,
      "name": {
        "it": "Donna",
        "en": "Women",
        "de": "Women"
      },
      "slug": {
        "it": "women",
        "en": "women",
        "de": "women"
      },
      "ancestors": [],
      "orderHint": "0.000014579626520791366299359",
      "createdAt": "2016-03-14T13:37:32.080Z",
      "lastModifiedAt": "2016-03-14T13:37:32.080Z",
      "externalId": "2",
      "lastMessageSequenceNumber": 1
    }
  ]
}]
Javadoc: http://commercetools.github.io/commercetools-jvm-sdk/apidocs/io/sphere/sdk/json/JsonException.html

Strangely enough, the stacktrace prints a query result with an object, which isn't a tax category, nor is it an existing object in the platform (e.g. Category).
The exception is also thrown when using TaxCategoryQuery.of() or by adding a query predicate e.g. for name.

This is a blocking issue for us.

**Comment by schleichardt** [comment]
That looks weird, but sadly the exception stack trace is not complete, it did not show what it sent to the API. Can you give me the whole stack trace? If it contains non-public data you can send it also to the support: https://sphere.atlassian.net/servicedesk/customer/portal/1/create/46

I checked out 1.6.0 and master and could not reproduce.

**Comment by fhaertig** [comment]
I need to apologies, we tracked down the problem to a misconfiguration with a TestDoubleSphereClient. After using the correct SphereClient. everything works as expected.
Thanks though for the fast response!
