### ISSUE TITLE
Check update of Moneta to 1.1

### ISSUE THREAD

**Issue by lauraluiz** [commercetools/commercetools-jvm-sdk#1264]
https://github.com/JavaMoney/jsr354-ri
Maybe it solves the recurring money issues we have.

**Comment by katmatt** [comment]
@lauraluiz I updated the moneta version without any problems and all of our unit tests are running successfully. But the moneta 1.1 release notes and the changed code didn't give me a clue if this update improves our issues :-( But of course it makes sense to update the version anyway.

**Comment by lauraluiz** [comment]
Yes, let's update it.

**Comment by katmatt** [comment]
I started to work on this last month, but then had some issues. I will take a look on it today.

**Comment by katmatt** [comment]
Another thing to keep an eye on is how the version update interferes with our OSGi support.

**Comment by katmatt** [comment]
@acbeni I started to work on the here: https://github.com/commercetools/commercetools-jvm-sdk/tree/update-to-moneta-1.1

Please review my changes and please fix any issues you come across.

**Comment by acbeni** [comment]
@katmatt for the change it seems straight forward so looks good, i think we should move forward with a pull request.
