### ISSUE TITLE
productCount in facets

### ISSUE THREAD

**Issue by schleichardt** [commercetools/commercetools-jvm-sdk#1270]
@peter-gerhard is there everything already implemented in the sdk? 

see platform doc: http://dev.commercetools.com/release-notes.html#release-notes---commercetools-platform---version-release-21112016

see https://github.com/commercetools/commercetools-jvm-sdk/pull/1219

**Comment by peter-gerhard** [comment]
@schleichardt yes

**Comment by schleichardt** [comment]
Thanks!
