### ISSUE TITLE
error on method ofUnsetAttribute for set of lenum attributes

### ISSUE THREAD

**Issue by stmeissner** [commercetools/commercetools-jvm-sdk#1275]
Given following attribute definition:

```json
{
  "name": "ProductFlags",
  "label": {
    "de": "Produkt Flag",
    "en": "Product flag"
  },
  "type": {
    "name": "set",
    "elementType": {
      "name": "lenum",
      "values": [
        {
          "key": "key_1",
          "label": {
            "de": "eins",
            "en": "one"
          }
        },
        {
          "key": "key_2",
          "label": {
            "de": "zwei",
            "en": "two"
          }
        }
      ]
    }
  },
  "attributeConstraint": "SameForAll",
  "isRequired": false,
  "isSearchable": true,
  "inputHint": "SingleLine",
  "displayGroup": "Other"
}
```
the code snippet for removing all lenum values in the Set attribute:
```java
sphereClient.execute(ProductUpdateCommand.of(product, SetAttributeInAllVariants.ofUnsetAttribute("ProductFlags"))).toCompletableFuture().join();
```
throws following error code:
```
  "statusCode" : 400,
  "message" : "The value '\"<undefined>\"' is not valid for field 'ProductFlags'. The value of the attribute must be the same across all variants.",
```
Expected behavior is to not receive such error since the attribute value should be removed on all variants of the product to be updated. Therefore the `sameForAll` constraint is not expected to be violated here.

Error occurred in RC1 of the SDK. To be checked with later versions, couldn't find a test for this particular case.

**Comment by schleichardt** [comment]
I will have a look today.

**Comment by schleichardt** [comment]
👎 for not showing the whole stack trace which shows what really happened.

I wrote a test and the update action worked for me as expected: https://github.com/commercetools/commercetools-jvm-sdk/commit/d76ec3e43c50671ce3f1036e8a58952a9734a6b5#diff-85fe3e814a43ba743a7c3067bb2f4364R60

But I got this error creating a product with just the attribute and nothing else.

@lauraluiz please review
