### ISSUE TITLE
ZoneDraftDsl Missing?

### ISSUE THREAD

**Issue by shanezr** [commercetools/commercetools-jvm-sdk#1283]
Just pulled the 1.8.0 tag and trying to build, ZoneDraft.java is referencing @JsonDeserialize(as = ZoneDraftDsl.class) but I'm not finding that class anywhere in the project or modules

**Comment by shanezr** [comment]
I think my builder just wasn't working properly.. I dropped and pulled the project again, then packaged and I see it in a compiled jar

**Comment by lauraluiz** [comment]
I guess you didn't have anymore problems then, but let us know if it is otherwise :)
