### ISSUE TITLE
java.lang.NoSuchMethodError: io.sphere.sdk.payments.PaymentDraftBuilder.build()Lio/sphere/sdk/payments/PaymentDraft;

### ISSUE THREAD

**Issue by heshamMassoud** [commercetools/commercetools-jvm-sdk#1284]
Hi,

When using jvm sdk version >= 1.7.0 with [Payone Integration Services](https://github.com/commercetools/commercetools-payone-integration), when we create a payment as follows:
```java
CreatePaymentDataBuilder paymentDataBuilder = CreatePaymentDataBuilder.of(sphereClient, selectedPaymentMethod, cart, orderNumber);
PaymentCreationResult paymentCreationResult = getPaymentAdapterService().createPayment(paymentDataBuilder.build()).toCompletableFuture().join();
```

 we get the following exception:
```java
Caused by: java.lang.NoSuchMethodError: io.sphere.sdk.payments.PaymentDraftBuilder.build()Lio/sphere/sdk/payments/PaymentDraft;
	at com.commercetools.sunrise.payment.methods.CreatePaymentMethodBase.removePaymentsAndCreateNew(CreatePaymentMethodBase.java:40)
	at com.commercetools.sunrise.payment.payone.methods.PayoneBanktransferInAdvanceCreatePaymentProvider.lambda$create$1(PayoneBanktransferInAdvanceCreatePaymentProvider.java:37)
	at com.commercetools.sunrise.payment.service.PaymentAdapterServiceImpl.createPayment(PaymentAdapterServiceImpl.java:64)
```

Seems like there is a  problem with how the `PaymentDraftBuilder` is generated (maybe?), especially that the method reference has this weird ending 
```
io.sphere.sdk.payments.PaymentDraftBuilder.build()Lio/sphere/sdk/payments/PaymentDraft;
```

Thanks!

**Comment by heshamMassoud** [comment]
@lauraluiz It appears that the problem was that the [Payment Module](https://github.com/commercetools/project-payment) was using a version of the SDK that is earlier that 1.7 (which introduced the draft builders code generation). Maybe it should be mentioned in the release notes that it's a breaking change :)

cc @ahalberkamp @andrii-kovalenko-ct

**Comment by lauraluiz** [comment]
Mentioned in the Release Notes that this can be a breaking change http://commercetools.github.io/commercetools-jvm-sdk/apidocs/io/sphere/sdk/meta/ReleaseNotes.html

The problem was simply that the method is now returning a covariant of the previous type (PaymentDraftDsl --|> PaymentDraft), which is apparently harmless but on bytecode level the method signature changes.
