### ISSUE TITLE
Expose PriceMode on LineItem

### ISSUE THREAD

**Issue by shanezr** [commercetools/commercetools-jvm-sdk#1285]
Would it be possible to add getPriceMode on io.sphere.sdk.carts.LineItem or is there another existing method to determine if ExternalLineItemTotalPrice has been set on a LineItem?

**Comment by lauraluiz** [comment]
@shanezr thanks for reporting it, we were not aware thing getter was missing. We will implement it in the next weeks. If you need it sooner you can also make a PR and I will review it.

**Comment by lauraluiz** [comment]
@shanezr the getter is exposed in released version 1.9.0
http://commercetools.github.io/commercetools-jvm-sdk/apidocs/io/sphere/sdk/meta/ReleaseNotes.html#v1_9_0
