### ISSUE TITLE
Attribute.getValueAsStringSet() does not preserve order of values 

### ISSUE THREAD

**Issue by fhaertig** [commercetools/commercetools-jvm-sdk#1294]
Hi,

The documentation for product attributes of type "Set" states: "The set attribute type defines a set (array without duplicates) with values of the given elementType" (http://dev.commercetools.com/http-api-projects-productTypes.html#settype). Since this definition is unclear about the order of values in the Set, we asked commercetools support a while ago. They said the order is retained as in any proper array.

However, this seems to be wrong as far as it concerns the jvm-sdk. The following Test fails even with sdk version 1.9.0:

` final String exampleProductJson = " {\n" +
               {...}
                "      \"masterData\": {\n" +
                "        \"current\": {\n" +
               {...}
                "          \"masterVariant\": {\n" +
               {...}
                "            \"attributes\": [\n" +
                "              {\n" +
                "                \"name\": \"testAttribute\",\n" +
                "                \"value\": [" +
                "                    \"3\",\n" +
                "                  \"1\",\n" +
                "                  \"2\"" +
                "              }\n" +
                "            ],\n" +
               {...}
                "    }";`

           ` final Product parsedProduct = SphereJsonUtils.readObject(exampleProductJson, Product.class);
            assertThat(parsedProduct.getMasterData().getCurrent().getMasterVariant().getAttribute("testAttribute").getValueAsStringSet())
                .containsExactly("3", "1","2");`

In contrast to the Admin-Center: here the attribute values are shown in the correct order.
Would be nice if we could see this fixed in the next sdk version.

Thank you!

**Comment by selo-ecube** [comment]
We would appreciate if you could publish a release this week that includes this fix.

**Comment by lauraluiz** [comment]
@selo-ecube yes for sure, we already have everything ready for the release since last week, but due to a technical issue we had to postpone it until this week. I'll let you know when this is released.

**Comment by lauraluiz** [comment]
Solved in https://github.com/commercetools/commercetools-jvm-sdk/releases/tag/v1.11.0
