### ISSUE TITLE
Generate maven source artifacts

### ISSUE THREAD

**Issue by katmatt** [commercetools/commercetools-jvm-sdk#1305]
We should add the maven source plugin to our build to generate maven source artifacts during or build/release. These source artifacts are then deployed with our release to maven central. And this will make it easier for our users to download the source code from their IDE (e.g. eclipse, idea) instead of having to access the correct branch on github..

**Comment by lauraluiz** [comment]
I'm surprised we didn't generate them yet 😮

**Comment by katmatt** [comment]
@lauraluiz was right, we already create source artifacts during our maven release process. Generation of source artifacts is generated by the "release" maven profile. No fix required ;-)
