### ISSUE TITLE
Implement Product Update Actions "staged" parameter

### ISSUE THREAD

**Issue by nkuehn** [commercetools/commercetools-jvm-sdk#1309]
To directly publish e.g. the prices that come from an external feed it's necessary to be able to directly publish the update sent. 

This is a supported API feature ( http://dev.commercetools.com/http-api-projects-products.html#set-prices ) but not in the SDK. 

There are a bunch of closed older issues (2015 etc) that mention the topic, but it's not clear why the API feature is not in the SDK.

**Comment by katmatt** [comment]
@nkuehn the current jvm sdk version is lacking the staged update action parameter for all update actions that support it. I would suggest to add it for all update actions and not just the setPrices update action.

**Comment by nkuehn** [comment]
right, I suspected that already but wanted to keep the scope on what I needed atm. 

I suggest you cross-check with the platform team what the background behind the topic is - it's relatively seldom that parameters are "forgotten".  

In fact, there is an old issue about it: https://github.com/commercetools/commercetools-jvm-sdk/issues/598  that implements a "stagedWrapper" in test code. 
https://github.com/commercetools/commercetools-jvm-sdk/blob/69d1bf9fad0aa72cdff6e238355761d2b1142dbc/commercetools-models/src/test/java/io/sphere/sdk/products/commands/ProductUpdateCommandIntegrationTest.java#L947

There may have been design reasons (maybe platform wanted to remove the possibility?), but they are opaque to me. 

@mmoelli do you remember what was the background here?
