### ISSUE TITLE
ProductVariantDraftBuilder#of method is missing assignment of key and assets fields

### ISSUE THREAD

**Issue by heshamMassoud** [commercetools/commercetools-jvm-sdk#1320]
`ProductVariantDraftBuilder#of` method is missing assignment of key and assets fields. And so it returns a builder that is missing those fields which have been already defined in the draft.
https://github.com/commercetools/commercetools-jvm-sdk/blob/master/commercetools-models/src/main/java/io/sphere/sdk/products/ProductVariantDraftBuilder.java#L34-L40

````java
    public static ProductVariantDraftBuilder of(final ProductVariantDraft productVariantDraft) {
        return of()
                .sku(productVariantDraft.getSku())
                .prices(productVariantDraft.getPrices())
                .attributes(productVariantDraft.getAttributes())
                .images(productVariantDraft.getImages());
    }
````

**Comment by katmatt** [comment]
@heshamMassoud Good catch and thanks for reporting this bug! I will fix it after implementing #1321.
