### ISSUE TITLE
Add Matthias Köster as dev

### ISSUE THREAD

**Issue by lauraluiz** [commercetools/commercetools-jvm-sdk#1324]
pom files

**Comment by katmatt** [comment]
@lauraluiz would this then allow me to get access to the Sonatype OSSRH nexus repository? So that I too can perform releases?

**Comment by katmatt** [comment]
And I would suggest to remove some redundancies in our pom.xml files.

**Comment by lauraluiz** [comment]
No, this is purely for having you in the  "credits" ;)

**Comment by katmatt** [comment]
Ok ;-)
