### ISSUE TITLE
PagedSearchResult missing @Nullable

### ISSUE THREAD

**Issue by lauraluiz** [commercetools/commercetools-jvm-sdk#1367]
All the `getFacetResult` and similar methods are actually returning `null` when the facet is not found, yet there is no annotation.

**Comment by katmatt** [comment]
@lauraluiz Similar methods are all methods that call `getFacetResult()`? Like `getFilteredFacetResult`, `getRangeFacetResult`and `getFilteredFacetResult`? Or am I missing other methods here?

**Comment by lauraluiz** [comment]
Yes, those are the ones I had in mind when I wrote that. Probably the one for AllRanges too.
