### ISSUE TITLE
Missing orderHint sort in CategoryQuery

### ISSUE THREAD

**Issue by lauraluiz** [commercetools/commercetools-jvm-sdk#1368]
We don't have `orderHint` in our CategoryQueryModel. This attribute's purpose is mainly for sorting, so unless it's discouraged to sort by it on the platform side (check), I would add it.

**Comment by lauraluiz** [comment]
BTW, I did a simple test in playground and it seems to work.

**Comment by katmatt** [comment]
Our `CategoryQueryModel` is generated from the `Category` interface, but we have disable generating of the query model for the `orderHint` with the `@IgnoreInQueryModel' annotation: [Category#getOrderHint()](https://github.com/commercetools/commercetools-jvm-sdk/blob/master/commercetools-models/src/main/java/io/sphere/sdk/categories/Category.java#L116)
