### ISSUE TITLE
idea: Helper to cast Product into ProductProjection

### ISSUE THREAD

**Issue by nkuehn** [commercetools/commercetools-jvm-sdk#1384]
A client's Import implementation is currently fetching every ProductProjection separately from the API after creating a Product.  Among others, this is done because the codebase of the next steps is implemented on ProductProjections (most products don't actually need to be changed, this is usually the case). 

They could have one reason less to fetch all the Products again if the SDK helped to build a ProductProjection out of a Product.  At the moment all the information is there, but even if in the future the APIs ProductProjection has more fields that would be useful. 

@MGA-dotSource FYI

**Comment by katmatt** [comment]
@nkuehn We have the [Product#toProjection(ProductProjectionType)](http://commercetools.github.io/commercetools-jvm-sdk/apidocs/io/sphere/sdk/products/Product.html#toProjection-io.sphere.sdk.products.ProductProjectionType-) method in our SDK for some time. Have you tried to using it?

**Comment by nkuehn** [comment]
hm, sorry for having been sloppy.  Did not find it ad hoc (searched for something like ProductProjection.of(Product)  which is not the standard pattern anyways
