### ISSUE TITLE
Unnessesary fb @nullable annotation on InventoryEntryDraft#getQuantityOnStock() method

### ISSUE THREAD

**Issue by heshamMassoud** [commercetools/commercetools-jvm-sdk#1399]
The method [`InventoryEntryDraft#getQuantityOnStock`](https://github.com/commercetools/commercetools-jvm-sdk/blob/master/commercetools-models/src/main/java/io/sphere/sdk/inventory/InventoryEntryDraft.java#L30) is marked as `@Nullable`.  Could the `quantityOnStock` ever be `null` actually?

As far as I can see, both the [public `of` factory methods](https://github.com/commercetools/commercetools-jvm-sdk/blob/master/commercetools-models/src/main/java/io/sphere/sdk/inventory/InventoryEntryDraft.java#L45-L53) require quantityOnStock as a parameter.

**Comment by katmatt** [comment]
Good catch, according to our documentation it's [mandatory](http://dev.commercetools.com/http-api-projects-inventory.html#inventoryentry). Thanks for reporting it and we'll fix it in our upcoming release.

**Comment by heshamMassoud** [comment]
@katmatt on the other hand as mentioned [here](https://github.com/commercetools/commercetools-sync-java/pull/19#discussion_r116971062); Through the JVM SDK, an `InventoryEntryDraft` object can be instantiated with a `null` `quantityOnStock` using the Draft builder as follows:-
````java
InventoryEntryDraft inventoryEntryDraft = InventoryEntryDraftBuilder.of("anySku", null).build();
````
so  in this sense it will be `nullable`, if `getQuantityOnStock` is called on this instance. 
But then I am kind of confused here because, users could pass nulls to any of the required fields and the draft instance will be created normally. Is this not validated on the SDK level? 

##### Side question
Are these `InventoryEntryDraft#of` left on the SDK on purpose? because they are not there for other drafts. If they are, then which should be used to instantiate a draft the InventoryEntryDraft or the InventoryEntryDraftBuilder?

**Comment by katmatt** [comment]
@heshamMassoud Ok, I see what causes your confusion. The source of truth is our documentation and there the `quantityOnStock` property is mandatory. And right now we just use the `@Nullable` annotation to document if a field or parameter is optional. Our SDK currently doesn't validate the fields or parameters and relies on the validation in our backend. 

And we decided to use non primitive parameter types for all of our builder classes, but if they aren't annotated with `@Nullable` they are logically mandatory.

And to your side question:
We plan to review of our code for factory methods on our resource types and will deprecate them soon. The plan is to force our users to always use a builder class to create objects. This will make the separation of concerns clear and avoid confusion in the future.

**Comment by heshamMassoud** [comment]
@katmatt thanks for the info!
