### ISSUE TITLE
Getter for sphere config/ project key through SphereClient

### ISSUE THREAD

**Issue by heshamMassoud** [commercetools/commercetools-jvm-sdk#1403]
### Description

It would be great to have on the `SphereClient` a getter for the the `SphereApiConfig`, or even the projectKey directly, to be able to get the project key easily just through the client without needing to have an instance of `SphereApiConfig` beforehand.

### Expected Behaviour
Ability to get the project key from a client like that:
````java
final SphereClient client = SphereClient.of(clientConfig, httpClient, tokenSupplier);
String projectKey = client.getConfig().getProjectKey();
````

or even better:

````java
final SphereClient client = SphereClient.of(clientConfig, httpClient, tokenSupplier);
String projectKey = client.getProjectKey();
````

### Current Behaviour
Currently it's not possible to access the config/project key from just the client.

### Context
In the [commercetools sync](https://github.com/commercetools/commercetools-sync-java/) library, a user of the library is expected to only pass a `sphereClient` to the library. So it doesn't actually know about the Config. However, the library needs to add the project key, when logging exceptions to the user for easier debugging. Therefore, with the current behaviour of the JVM SDK, the user would need to pass the config as well so the library can have this project key.

**Comment by katmatt** [comment]
I think the initial idea was to not expose the client configuration. But since you can't create a client without a config and also understand your use case, I like the idea to expose the configuration with a `getConfig()` method 👍
