### ISSUE TITLE
Add @include.example to generated update actions

### ISSUE THREAD

**Issue by katmatt** [commercetools/commercetools-jvm-sdk#1419]
We now use our update action code generator in several places and I think it helps us to improve the consistency of our SDK. But our automatically created update actions don't provide a link to an example as most of our manually created update actions do. 

It would be nice if our update action generator could add a link to an example with our custom `@include.example` javadoc tag.

We could either:

- derive the link from our integration test naming convention
- or replace our `@HasUpdateActions` and `@HasNoUpdateAction` annotation with a new method annotation `@HasUpdateAction` where we could add a property `includeExample` to provide a link to an example

**Comment by ccsalazarr-commercetools** [comment]
It was already implemented the possibility to assign an example link as a parameter in the `@HasUpdateActions` annotation. Now I change it to allow also an example link by default, without creating new method annotations.
