### ISSUE TITLE
Add isExpanded method to Reference class

### ISSUE THREAD

**Issue by katmatt** [commercetools/commercetools-jvm-sdk#1423]
After reviewing sunrise code, we realized that it would be nice to have a `isExpanded` method on our `io.sphere.sdk.models.Reference` class. The method should return `true` if the reference is expanded (`getObj() != null`). 

This will then allow our users to use the stream filter method with a method reference: `getReferences().streams().filter(Reference::isExpanded)`.

**Comment by lauraluiz** [comment]
Oops, sorry 😬 
At least you explained it much better, let's put a duplicated #1422

**Comment by katmatt** [comment]
Don't be sorry for being faster than me 😄 And great that you linked the issues 👍
