### ISSUE TITLE
Add revapi maven check goal to build

### ISSUE THREAD

**Issue by katmatt** [commercetools/commercetools-jvm-sdk#1432]
Currently we are using the revapi maven goal `report` when we release our SDK. The revapi maven plugin provides the goal `check`, which fails the build if there was a breaking change to our public API that isn't reflected in the current version.

We should try to integrate the `check` goal into our build, so that we have to update the project version before we do a pull request. This would help us in releasing our SDK, because the project version on master would then conform to the semantic versioning scheme enforced by the `check` goal.

References:

- [Revapi Project](http://revapi.org/)
- [Revapi Maven Plugin](http://revapi.org/modules/revapi-maven-plugin/index.html)
- [Revapi Maven Plugin `check` goal](http://revapi.org/modules/revapi-maven-plugin/check-mojo.html)

**Comment by katmatt** [comment]
You can find some docs how we currently run revapi with maven here: https://github.com/commercetools/commercetools-jvm-sdk/blob/master/commercetools-models/pom.xml#L98

**Comment by ccsalazarr-commercetools** [comment]
When there are breaking changes, there will be generated a report per maven module and one aggregated report. If we use the `check` goal, the build would fail when there are breaking changes, no matter if we have already updated the version.
