### ISSUE TITLE
CustomFields copy factory methods copies the `TypeId` instead of the `id` of the Type

### ISSUE THREAD

**Issue by heshamMassoud** [commercetools/commercetools-jvm-sdk#1444]
### Description
There is a bug in the copy factory method of custom fields. It happens when building a `CutomFieldsDraft` instance from a `CustomFields` instance. The `id` is confused with the `TypeId`. 

I noticed it when converting a list of `Category`s to `CategoryDrafts` with custom fields. I got the following response from the platform:
```json
http response formatted body: {
  "statusCode" : 400,
  "message" : "Request body does not contain valid JSON.",
  "errors" : [ {
    "code" : "InvalidJsonInput",
    "message" : "Request body does not contain valid JSON.",
    "detailedErrorMessage" : "actions -> type -> id: Invalid UUID: 'type'"
  } ]
}
````
### The problem
The problem is here in this [line](https://github.com/commercetools/commercetools-jvm-sdk/blob/master/commercetools-models/src/main/java/io/sphere/sdk/types/CustomFieldsDraftBuilder.java#L58):
````java
public static CustomFieldsDraftBuilder of(final CustomFields customFields) {
        final Reference<Type> type = customFields.getType();
        return new CustomFieldsDraftBuilder(type.getTypeId(), type.getKey()).fields(customFields.getFieldsJsonMap());
    }
```` 
This causes the Custom Type to have the id "type" (which is the `typeId`) instead of an actual `id`.

### The fix
````java
public static CustomFieldsDraftBuilder of(final CustomFields customFields) {
        final Reference<Type> type = customFields.getType();
        return new CustomFieldsDraftBuilder(type.getId(), type.getKey()).fields(customFields.getFieldsJsonMap());
    }
````

**Comment by heshamMassoud** [comment]
Also seems that this [line](https://github.com/commercetools/commercetools-jvm-sdk/blob/master/commercetools-models/src/main/java/io/sphere/sdk/types/CustomFieldsDraftBuilder.java#L33) might be wrong:
````java
typeId = customFieldsDraft.getType().getTypeId();
````

shouldn't it be:
````java
typeId = customFieldsDraft.getType().getId();
````
?

**Comment by katmatt** [comment]
@heshamMassoud Good catch and thanks for reporting this bug! I especially like that you already provided the patch 😄 In case you find another issue and have a fix for it, you can also add a PR to your issue. We always welcome contributors 😉 

I will assign it to Christian and he will take a look at it tomorrow. May be we can fix it this week so that it will be part of the release we plan for this week.

**Comment by heshamMassoud** [comment]
@katmatt @ccsalazarr-commercetools thanks guys! next time I will create a PR 😉

**Comment by heshamMassoud** [comment]
@katmatt @ccsalazarr-commercetools BTW, this fixes it only in the builder classes. But copy methods like `CustomFieldsDraft.of` still have a logical bug [here](https://github.com/commercetools/commercetools-jvm-sdk/blob/master/commercetools-models/src/main/java/io/sphere/sdk/types/CustomFieldsDraft.java#L32). I am aware that we should use the builders from now on. But still some people might use the normal `CustomFieldsDraft.of` 😉 

If I have time later today, I will make a PR :)

**Comment by ccsalazarr-commercetools** [comment]
I have changed the `CustomFieldsDraft`, I replaced the uses of `typeId` by `id`. I have already created a PR :)

**Comment by katmatt** [comment]
@heshamMassoud Cristian (@ccsalazarr-commercetools) has already fixed this and will add a test for it. We plan to release the fix next week.
