### ISSUE TITLE
Description value in setDescription is required in CTP 

### ISSUE THREAD

**Issue by heshamMassoud** [commercetools/commercetools-jvm-sdk#1454]
Description value in setDescription update action for Categories is required in CTP: http://dev.commercetools.com/http-api-projects-categories.html#set-description

However, it is annotated `@Nullable` in the SDK:

https://github.com/commercetools/commercetools-jvm-sdk/blob/master/commercetools-models/src/main/java/io/sphere/sdk/categories/commands/updateactions/SetDescription.java#L20

**Comment by katmatt** [comment]
@heshamMassoud I think that this is an issue in our documentation: The `description` property of a category is marked as optional [Category](http://dev.commercetools.com/http-api-projects-categories.html#category) and its  update action follows our naming conventional for optional properties `Set<PropertyName>`, the `description` property of the `SetDescription` update action should be optional too. 

We should open a PR for our documentation and close this issue.

**Comment by heshamMassoud** [comment]
cc: @ValeSauer

**Comment by ValeSauer** [comment]
documentation will be fixed with https://github.com/sphereio/dev.commercetools.com/pull/613
