### ISSUE TITLE
Reclassification of change in 1.21.0

### ISSUE THREAD

**Issue by selo-ecube** [commercetools/commercetools-jvm-sdk#1477]
Could you re-classify

`CHANGE: Changed type of ProductDraft.getCategories() to ResourceIdentifier. This change doesn't require changes to your source code, but requires a recompilation of all projects that depend on this class.`

to

`REMOVE: ... <with adjusted details>`

Since the method now returns `ResourceIdentifier`s that do not have a getObj() method that used to be provided by the previously-returned`Reference`s.

Thanks!

**Comment by katmatt** [comment]
@selo-ecube Thanks for raising this issue and I hope that it didn't cause a lot of problems for you. In retrospect it may have been better to bump the major version, but then we would have to maintain separate versions of our SDK and we thought that this change didn't cause a lot of trouble. And it never made sense that the `ProductDraft`s accepted category references.

But I agree that we should reclassify the change in our release notes and will fix it today.

**Comment by katmatt** [comment]
@selo-ecube I still think that we should classify it as a `CHANGE`, which according to our legend can be a breaking change. But we should document that it requires changes in your source code. What do you think?

**Comment by selo-ecube** [comment]
Using `CHANGE` instead of `REMOVE` is also a valid choice, yes. Maybe you could modify the description of the change.

> This breaking change requires an update of your source code. 

This sentence could be relaxed and have some more detail to allow API users to evaluate the change: "This breaking change may require an update of your source code, depending on how you use the API. E.g. the previously returned Reference instances provided a getObj() method that is not available from ResourceIdentifier."

> But since our backend never used the additional properties (Reference.getObj() ) of the Reference, changing the type from Reference<Category> to ResourceIdentifier<Category> shouldn't require additional changes to your source code. 

This sentence contradicts the statement of your previous sentence of the description. I would simply remove it because it doesn't help API users to hear the backend did not use getObj() if the API users did in fact use the method ;-). That's what happened in our case: We used the information from the `Category` object in error messages. Now that we cannot obtain the `Category` anymore, we need to add keys (not just externalIds) to our Categories so we can obtain the key from the Category and use it in log messages. It's a good thing to be able to access categories via keys, though. 

Thanks for your help!

**Comment by katmatt** [comment]
@selo-ecube Thanks for your input, it was very helpful 👍 I improved the change description based on your input and will publish the updated release notes today.
