### ISSUE TITLE
Update test dependencies to latest version

### ISSUE THREAD

**Issue by katmatt** [commercetools/commercetools-jvm-sdk#1518]
As suggested in a pull request, we should update all of our test dependencies to the latest version.

**Comment by andrii-kovalenko-ct** [comment]
and then (at least in the new tests) use more convenient assertions, like:

[containsExactlyInAnyOrder](http://joel-costigliola.github.io/assertj/core/api/org/assertj/core/api/ListAssert.html#containsExactlyInAnyOrder(ELEMENT...))
