### ISSUE TITLE
ProductDraft#masterVariant is optional by API, but has no explicit @Nullable in SDK

### ISSUE THREAD

**Issue by andrii-kovalenko-ct** [commercetools/commercetools-jvm-sdk#1559]
By the [platform API](http://dev.commercetools.com/http-api-projects-products.html#productdraft) `ProductDraft#masterVariant` is an optional value.

As i see the common convention in the JVM SDK is that all nullable values are marked `@Nullable` explicitly, when annotation for mandatory values is omitted.

Thus [`ProductDraft#getMasterVariant()`](https://github.com/commercetools/commercetools-jvm-sdk/blob/master/commercetools-models/src/main/java/io/sphere/sdk/products/ProductDraft.java#L56) as same as [`ProductDraftBuilder#of()`](https://github.com/commercetools/commercetools-jvm-sdk/blob/master/commercetools-models/src/main/java/io/sphere/sdk/products/ProductDraftBuilder.java#L37) are confusing, because they don't have explicit annotations.

More on that: [master variant is assigned automatically from the variants](https://github.com/commercetools/commercetools-jvm-sdk/blob/master/commercetools-models/src/main/java/io/sphere/sdk/products/ProductDraftBuilder.java#L31), if it is **null**.

So, looks like `@Nullable` annotation is missing on both `ProductDraft#getMasterVariant()` (including `ProductVariantDraft masterVariant;`) and `ProductDraftBuilder#of()`

**Comment by katmatt** [comment]
This indeed looks like missing annotations. We're currently busy with more important issues, but as always we are open to contributions ;-)

**Comment by andrii-kovalenko-ct** [comment]
from `master`?

**Comment by katmatt** [comment]
Yes, please 😄
