### ISSUE TITLE
Add CategoryTree.findByKey(String)

### ISSUE THREAD

**Issue by selo-ecube** [commercetools/commercetools-jvm-sdk#1568]
Since categories now have a key, it would be nice to be able to get them from the [CategoryTree](https://github.com/commercetools/commercetools-jvm-sdk/blob/master/commercetools-models/src/main/java/io/sphere/sdk/categories/CategoryTree.java) by key.

**Comment by katmatt** [comment]
That's a good idea 👍 We'll try to add it to our next release 😄
