### ISSUE TITLE
Getters for generated draft builders

### ISSUE THREAD

**Issue by andrii-kovalenko-ct** [commercetools/commercetools-jvm-sdk#1572]
In current implementation `ProductDraftBuilder` and [`PriceDraftBuilder`](https://github.com/commercetools/commercetools-jvm-sdk/blob/81410143bd9e2a4f3fae362f8586984b1c7eb1d1/commercetools-models/src/main/java/io/sphere/sdk/products/PriceDraftBuilder.java) are implemented as java sources and both have getters.
(`ProductDraftBuilder` is generated from [`ProductDraft`](https://github.com/commercetools/commercetools-jvm-sdk/blob/69d9dc7095bbb8fa208ddaa39ea90c05f1398430/commercetools-models/src/main/java/io/sphere/sdk/products/ProductDraft.java#L26-L26) with _gettersForBuilder = true_)

In the same time [`CategoryDraftBuilder`](https://github.com/commercetools/commercetools-jvm-sdk/blob/d4553aee96a7710bef75bbce552fb4a7aa8c2ef6/commercetools-models/src/main/java/io/sphere/sdk/categories/CategoryDraft.java#L20-L21) and [`InventoryEntryDraftBuilder`](https://github.com/commercetools/commercetools-jvm-sdk/blob/177df2dd772f3a2981adbe99d8fe96ffc9942505/commercetools-models/src/main/java/io/sphere/sdk/inventory/InventoryEntryDraft.java#L18-L26) don't have any getters - they are built without _gettersForBuilder = true_

1. This is inconsistent a bit with each other

2. In [`commercetools-java-sync`](https://github.com/commercetools/commercetools-sync-java/pull/146#issuecomment-336159420) project project we build update actions for different entities, and some times we need to read/write values on the builders. Otherwise we have to build/rebuild the drafts on each property update recalculation.
For example:
[`InventoryReferenceResolver`](https://github.com/commercetools/commercetools-sync-java/blob/b4fc61eb69423a41f71446c1cfc0d11aad607064/src/main/java/com/commercetools/sync/inventories/helpers/InventoryReferenceResolver.java#L93-L110) needs `InventoryEntryDraft` instance to read sku, and then `InventoryEntryDraftBuilder` to set updated channels.

**Conclusion**:
pls, update the JVM SDK auto-generated draft builders (guess, not only Categories and Inventories) to make them readable/consistent with other draft builders.

P.S. I could contribute if we are agree on the point that all draft builders should be readable.

**Comment by andrii-kovalenko-ct** [comment]
@katmatt  looks  like this code snippet has redundant empty `@FactoryMethod` entry:
https://github.com/commercetools/commercetools-jvm-sdk/blob/82a89ed0fb26ffc31fd44f816dca990daf0c5e99/commercetools-models/src/main/java/io/sphere/sdk/productdiscounts/ProductDiscountDraft.java#L12-L16

WDYT?

**Comment by katmatt** [comment]
The first `@FactoryMethod` annotation isn't redundant, because it triggers the creation of a parameterless `of` factory method. And we need this parameterless factory method to stay backwards compatible with previous JVM SDK versions. 

BTW: we are using the `revapi` maven plugin to check the backwards compatibility of our JVM SDK and this might be useful for you too.
