### ISSUE TITLE
Remove @ResourceDraftValue#gettersForBuilder

### ISSUE THREAD

**Issue by katmatt** [commercetools/commercetools-jvm-sdk#1580]
After we fixed #1572 we should remove the `@ResourceDraftValue#gettersForBuilder` and always generate getters for our `DraftBuilder` classes. This makes sure that our classes are more consistent in the future.

**Comment by andrii-kovalenko-ct** [comment]
>are more inconsitent in the future.

@katmatt guess you mean _more consistent_

**Comment by katmatt** [comment]
Ups and good catch 🥇 I corrected the description 👍
