### ISSUE TITLE
Bug in EnumLikeAttributeMapperImpl#serialize

### ISSUE THREAD

**Issue by heshamMassoud** [commercetools/commercetools-jvm-sdk#1619]
When creating an attribute draft with localized enum value as follows:

````java
final LocalizedString localizedString = LocalizedString.of(Locale.GERMAN, "german-text");
final LocalizedEnumValue localizedEnumValue = LocalizedEnumValue.of("key", localizedString);
final AttributeDraft attributeDraft = AttributeDraft.of(AttributeAccess.ofLocalizedEnumValue().ofName("name"), localizedEnumValue);
````
the JSON node value is serialised wrong and only the key of the enum is taken without the localized label of the enum. Running a simple assertion on the aformentioned draft as follows:
````java
assertThat(attributeDraft.getValue()).isEqualTo(localizedEnumValue);
````
leads to:
````java
org.junit.ComparisonFailure: 
Expected :LocalizedEnumValueImpl[key=key,label=LocalizedString(de -> german-text)]
Actual   :"key"
````

Probable reason of bug here: 
https://github.com/commercetools/commercetools-jvm-sdk/blob/master/commercetools-models/src/main/java/io/sphere/sdk/products/attributes/EnumLikeAttributeMapperImpl.java#L14

**Comment by heshamMassoud** [comment]
@katmatt when should we expect this to be fixed?

**Comment by katmatt** [comment]
@heshamMassoud We plan to release a bug fix next week.

**Comment by heshamMassoud** [comment]
@katmatt thanks :)
