### ISSUE TITLE
PagedSearchResult.empty() missing

### ISSUE THREAD

**Issue by lauraluiz** [commercetools/commercetools-jvm-sdk#1662]
PagedQueryResult.empty() does exist, but not its "search" counterpart.

**Comment by acbeni** [comment]
@lauraluiz you want it as a helper method to indicate the result is empty?

**Comment by acbeni** [comment]
@lauraluiz can describe what you mean by a search method?

**Comment by lauraluiz** [comment]
`PagedSearchResult.empty()` method does exist (https://github.com/commercetools/commercetools-jvm-sdk/blob/master/commercetools-sdk-base/src/main/java/io/sphere/sdk/queries/PagedQueryResult.java#L23), but we have no `PagedQueryResult.empty()` method. We should have it either on both sides or none (and I vote for both sides because it's useful to me).
