### ISSUE TITLE
Javadoc doesn't contain commands and queries for product types

### ISSUE THREAD

**Issue by katmatt** [commercetools/commercetools-jvm-sdk#1681]
Our published javadoc (http://commercetools.github.io/commercetools-jvm-sdk/apidocs/index.html) doesn't contain the full documentation for the `producttypes.queries` and `producttypes.commands` packages. For example it doesn't contain documentation for our `ProductTypeCreateCommand` or our `ProductTypeQuery` interfaces. This is really strange...

**Comment by schleichardt** [comment]
The update action SetParcelItems can also not be found in Javadoc.

**Comment by katmatt** [comment]
In fact it doesn't contain any of our generated java classes.
