### ISSUE TITLE
evaluate jackson-module-afterburner

### ISSUE THREAD

**Issue by schleichardt** [commercetools/commercetools-jvm-sdk#169]
https://github.com/FasterXML/jackson-module-afterburner

**Comment by schleichardt** [comment]
https://github.com/FasterXML/jackson-modules-base/tree/master/afterburner

@ccsalazarr-commercetools please check the total test time with and without that Jackson module

you can add it in SphereJsonUtils, I think

**Comment by ccsalazarr-commercetools** [comment]
After running some tests without using the AfterBurner module, and then running the same tests using the AfterBurner module, it didn't show any significative improvement on the performance. Therefore it will remain without the module.
