### ISSUE TITLE
Clearify update strategy for ResolvableResource

### ISSUE THREAD

**Issue by katmatt** [commercetools/commercetools-jvm-sdk#1697]
With our current implementation importing an unresolved resource updates the attributes and duplicates the references. We should fix this, but should discuss what should happen when the same unresolved resource is imported twice.

**Comment by katmatt** [comment]
I added this issue to the wrong github repository and that's why I closed it 😉

**Comment by acbeni** [comment]
@katmatt Good, i felt bad for not knowing what you are talking about after all this time working on the SDK 😅
