### ISSUE TITLE
add helper getTargetsMap

### ISSUE THREAD

**Issue by schleichardt** [commercetools/commercetools-jvm-sdk#1699]
In the class ItemShippingDetails is a getter for the details as list, but the list modelling is not so useful to the user, so it would be nice to add a default method like this:

```java
default Map<String, Integer> getTargetsMap() {
  return getTargets().stream()... // convert to map of addressKey pointing to the quantity
}
```

Also a creator with a map for the draft object could be an option

**Comment by acbeni** [comment]
Added to v1.30.0

**Comment by schleichardt** [comment]
thanks
