### ISSUE TITLE
Fix bootstrap problem with mirror-subclass-plugin

### ISSUE THREAD

**Issue by katmatt** [commercetools/commercetools-jvm-sdk#1700]
When I checkout the current source code and try to build it locally, the build fails with the attached log because it can't resolve the SNAPSHOT version of our `mirror-subclass-plugin`. 

It doesn't matter if I run `mvn clean install -DskipTests` before.

**Comment by katmatt** [comment]
[log.txt](https://github.com/commercetools/commercetools-jvm-sdk/files/1720180/log.txt)

**Comment by katmatt** [comment]
We can either:

- add the plugin to our release and use the released version
- put the plugin into a separate github repo, release it and use the released version

**Comment by katmatt** [comment]
May be setting the `relativePath` to the parent pom already helps here?

**Comment by katmatt** [comment]
Adding the `relativePath` worked on our bugfix branch `v1.29` and we should add it to our master.

**Comment by katmatt** [comment]
@schleichardt We merged our fix to master and it would be great if you could try to build our JVM SDK on your local machine 😄

**Comment by schleichardt** [comment]
```
[INFO] BUILD SUCCESS
```
