### ISSUE TITLE
"ofSkuAndAssetKeyAndAssetKey" Method name typo? 

### ISSUE THREAD

**Issue by heshamMassoud** [commercetools/commercetools-jvm-sdk#1702]
Seems like there is a typo in this method name
https://github.com/commercetools/commercetools-jvm-sdk/blob/04888b21ad7780b151e031db35af918df78b4830/commercetools-models/src/main/java/io/sphere/sdk/products/commands/updateactions/SetAssetCustomType.java#L103-L105

Shouldn't it be just `ofSkuAndAssetKey`?

**Comment by acbeni** [comment]
👍 thanks @heshamMassoud , actually it's a typo, it will be fixed with next release.

**Comment by acbeni** [comment]
Snyc report shows that the vulnerability exists on 2.9.4 which is the last version, the best we can do is wait for it to be fixed in the next release.
