### ISSUE TITLE
Fix reported vulnerabilities

### ISSUE THREAD

**Issue by katmatt** [commercetools/commercetools-jvm-sdk#1709]
Right now our github badges show that we have some vulnerabilities and we have to fix them.

**Comment by katmatt** [comment]
We still have some issues reported, looks like they're caused by transitive dependencies.

**Comment by acbeni** [comment]
This vulnerability still exists in the latest jackson release, the best we can do is wait for the next version.

**Comment by katmatt** [comment]
We should try to use the latest `2.9.5` release.
