### ISSUE TITLE
Could you make io.sphere.sdk.products.ProductLike public?

### ISSUE THREAD

**Issue by selo-ecube** [commercetools/commercetools-jvm-sdk#1711]
* I currently have an issue comparable to https://stackoverflow.com/questions/21434941/java-lang-illegalaccesserror-while-running-mockito-from-sbt :
* We mock a `ProductProjection` using Mockito. For whatever reason, Mockito involves the super-interface `ProductLike` in the game and due to sbt classloading this likely fails because `ProductLike` is package-protected.
* Since `CartLike` is a comparable interface and is public: Could you make `ProductLike` public as well?

Thanks!

**Comment by katmatt** [comment]
You're right, the `ProductLike` interface doesn't make a lot of sense with the default visibility. We will change it to `public` with our next release. Thanks for reporting this issue 🥇 👍
