### ISSUE TITLE
Cart API Extensions resourceTypeId naming conflict

### ISSUE THREAD

**Issue by lauraluiz** [commercetools/commercetools-jvm-sdk#1716]
Not sure if this is only a JVM SDK's naming issue or comes from the platform, but:

The `TriggerBuilder` class constructor is expecting something called "resourceTypeId" as first argument, although when creating an extension for cart the following is correct:
```
TriggerBuilder.of(Cart.referenceTypeId(), singletonList(TriggerType.CREATE)).build()
```
Whereas the following is not, because `Cart.resourceTypeId()` returns "order", instead of "cart" as the Trigger is expecting:
```
TriggerBuilder.of(Cart.resourceTypeId(), singletonList(TriggerType.CREATE)).build()
```

**Comment by acbeni** [comment]
In the documentation https://docs.commercetools.com/http-api-projects-api-extensions.html#trigger the attribute name is stated as `resourceTypeId`, in the tests i put `Cart.referenceTypeId()` just to avoid writing `"cart"` as a literal .
Now why `Cart.resourceTypeId()` returns `"order"` i have no idea, maybe it's a historical reason that i am not aware of. but there is a new addition in the extension from the backend, and i think i will have to enhance type safety in resource id to have only allowed types from backend (for example so far onl cart).

**Comment by lauraluiz** [comment]
> Now why Cart.resourceTypeId() returns "order" i have no idea

I think it might be related to custom types, as the type ID for both carts and orders is "order".
