### ISSUE TITLE
Update SDK badges

### ISSUE THREAD

**Issue by acbeni** [commercetools/commercetools-jvm-sdk#1734]
Our official docs doesn't contain badges for our releases,

we should fix this.

**Comment by katmatt** [comment]
Would be great if you could update them 🥇 
@jenschude implemented some magic to update them, how about asking him how to do it?

**Comment by katmatt** [comment]
Fixed and deployed to docs.commercetools.com. We now just have to discuss how we can add updating of the sdk badges into our process ;-)
