### ISSUE TITLE
PaymentDraftBuilder is missing the ability to set anonymousId.

### ISSUE THREAD

**Issue by garfailed** [commercetools/commercetools-jvm-sdk#1737]
According to the [documentation](https://docs.commercetools.com/http-api-projects-payments.html#paymentdraft) we should be able to set the `anonymousId` on a `PaymentDraft`, however currently it's not present.

![idea64_2018-04-04_11-50-50](https://user-images.githubusercontent.com/7635715/38300958-888d58b2-37fe-11e8-8133-2a74e0821032.png)

**Comment by acbeni** [comment]
@garfailed thanks for pointing out this 🥇 , actually i have checked the API, and both, `Payment` and `PaymentDraft` don't contain anonymous id which they should, we will fix this issue in the next release.

**Comment by katmatt** [comment]
The `anonymousId` and the corresponding `setAnonymousId` update action is completely missing in our SDK :-( We will add them and then you'll be able to set `anonymousId` via our `PaymentDraftBuilder` too :-)
