### ISSUE TITLE
Add method to decorate ObjectMapper with CTP config

### ISSUE THREAD

**Issue by katmatt** [commercetools/commercetools-jvm-sdk#1746]
@nkuehn provided a small patch that adds a new method `decorateObjectMapper` to our `SphereJsonUtils` class that. This method adds the configuration required by our JVM SDK to the given jackson object mapper and is very useful when implementing API extensions or using our subscriptions.

I would apply the patch and rename the method to `configureObjectMapper`, because it better reflects the intention of this method.

**Comment by nkuehn** [comment]
good idea to rename - it sounded too near to "decorator pattern" for me anyways.  And thanks for promoting the idea !
