### ISSUE TITLE
ProductType#AddAttributeDefinition update action is not according to commercetools API spec

### ISSUE THREAD

**Issue by jortizsao** [commercetools/commercetools-jvm-sdk#1786]
The class `AddAttributeDefinition` (http://commercetools.github.io/commercetools-jvm-sdk/apidocs/io/sphere/sdk/producttypes/commands/updateactions/AddAttributeDefinition.html) expects an `AttributeDefinition` (not an `AttributeDefinitionDraft`) in the constructor. 

But the commercetools API states that `addAttributeDefinition` (https://docs.commercetools.com/http-api-projects-productTypes#add-attributedefinition) expects an `AttributeDefinitionDraft`

**Comment by acbeni** [comment]
@jortizsao Thanks for your remark, this is actually a fix that needs o be done in the sdk, i will schedule it for the next release.
