### ISSUE TITLE
CustomFieldsDraftBuilder does not work well transitively

### ISSUE THREAD

**Issue by selo-ecube** [commercetools/commercetools-jvm-sdk#1788]
I'm doing

```java
final CustomFieldsDraft initialDraft = CustomFieldsDraftBuilder
                        .ofTypeKey("foo")
                        .addObject("field1", "value1")
                        .build()
// and then, in another component:
final CustomFieldsDraft extendedDraft = CustomFieldsDraftBuilder
                        .of(initialDraft)
                        .addObject("field2", "value2")
                        .build()
```

The method call `addObject("field2", "value2")` yields an `UnsupportedOperationException` because the constructor `CustomFieldsDraftBuilder.of(CustomFieldsDraft)` uses `customFieldsDraft.getFields()` internally, which returns an immutable copy of fields created by `CustomFieldsDraftImpl(String,String,Map)`.

I can work around this, but it would be nice if you could fix this :-). Thanks!

**Comment by acbeni** [comment]
Thanks for reporting (and analyzing 🏅) the bug 😄 .

This would be fixed in the next release for our SDK.
