### ISSUE TITLE
Update AddVariant update action

### ISSUE THREAD

**Issue by acbeni** [commercetools/commercetools-jvm-sdk#1866]
The `addVariant` update action now includes an `assets` field for providing images when creating a Product Variant.

**Comment by praveenkumarct** [comment]
According to the documentation [AddVariant](https://github.com/commercetools/commercetools-jvm-sdk/blob/master/commercetools-models/src/main/java/io/sphere/sdk/products/commands/updateactions/AddVariant.java#L38) should accept a list of  AssetDraft, but currently AddVariant expects a list of Assets.

**Comment by jenschude** [comment]
I opened a new issue as this 2 year old one can easily be overlooked.

**Comment by ashishhk** [comment]
Link to the new issue https://github.com/commercetools/commercetools-jvm-sdk/issues/2126
