### ISSUE TITLE
improve documentation about client configuration

### ISSUE THREAD

**Issue by stmeissner** [commercetools/commercetools-jvm-sdk#1910]
## What?

On https://commercetools.github.io/commercetools-jvm-sdk/apidocs/io/sphere/sdk/meta/GettingStarted.html

Please describe how to configure the Auth and API endpoints in section **_Instantiation_** depending on which platform region (EU/US) should be used.

## Why?
Customers have difficulties figuring out how to configure the endpoints

**Comment by skyriakou** [comment]
0,5 days
