### ISSUE TITLE
Cannot set delivery items to ParcelDraft

### ISSUE THREAD

**Issue by FL-K** [commercetools/commercetools-jvm-sdk#1996]
Currently there is no way to set the deliveryItems for a particular parcel.
Please add the method below to  io.sphere.sdk.orders.ParcelDraft;

`
static ParcelDraft of(final TrackingData trackingData, List<DeliveryItem> deliveryItems) {
        return new ParcelDraftDsl(deliveryItems, null, trackingData);
    }
`

**Comment by alex-ct** [comment]
Hello FL-K,

You can use a ParcelDraftBuilder to do it until we add a new method to the ParcelDraft.
