### ISSUE TITLE
Update url scheme for all SDKs

### ISSUE THREAD

**Issue by skyriakou** [commercetools/commercetools-jvm-sdk#2006]
Issue related to: https://wiki.commercetools.com/display/SRE/2019-06-14+URL+Schema

###Acceptance criteria:

- [ ] Url scheme is updated as stated above and added release note informing users of the change for the following SDKs
- [x] PHP
- [x] JAVA
- [x] node
- [x] .NET
- [ ] typescript

**Comment by katmatt** [comment]
@jenschude Why did you reopen this issue? I thought we track the progress in the individaual github issue trackers?

**Comment by jenschude** [comment]
I think it was because of the not completed checkboxes when I remember it right. ;)

**Comment by ashishhk** [comment]
Discussed with team, its mostly done for all the SDKs, no reason was identified to keep it open.
