### ISSUE TITLE
Fix Github Security Vulnerabilities JVM SDK

### ISSUE THREAD

**Issue by ashishhk** [commercetools/commercetools-jvm-sdk#2018]

**Comment by katmatt** [comment]
This security alert was invalid, it suggested that we should update `jackson-databind` to a version >= 2.9.10.4. But we already use version 2.10.1 (as can be seen here: https://github.com/commercetools/commercetools-jvm-sdk/blob/3ae0afe51ba9d30a5f63f93cdebccbb9e5df993d/pom.xml#L88). 
I checked it by running the command 
``mvn dependency:tree | grep jackson-databind`` 
which produced the following result:
``
[INFO] +- com.fasterxml.jackson.core:jackson-databind:jar:2.10.1:compile
[INFO] +- com.fasterxml.jackson.core:jackson-databind:jar:2.10.1:compile
``

**Comment by ashishhk** [comment]
thanks for checking @katmatt .
