### ISSUE TITLE
Type mismatch for 2 ResourceIdentifier fields.

### ISSUE THREAD

**Issue by ahmetoz** [commercetools/commercetools-jvm-sdk#2052]
Some fields should be changed from `Reference` to `ResourceIdentifier`.

ProductDraft#state
https://github.com/commercetools/commercetools-jvm-sdk/blob/28d88c7a4f57ccc825f5f318cc409c28d542fbac/commercetools-models/src/main/java/io/sphere/sdk/products/ProductDraft.java#L70

ShoppingListDraft#customer

https://github.com/commercetools/commercetools-jvm-sdk/blob/cfa043b25ebec1656311643ca4201ec81a172fe2/commercetools-models/src/main/java/io/sphere/sdk/shoppinglists/ShoppingListDraft.java#L33

**Comment by ashishhk** [comment]
It will be changed in our new version of Java SDK, we'll update you via your support ticket.

Thanks.
