### ISSUE TITLE
SetCustomerGroup action needs to support ResourceIdentifier.

### ISSUE THREAD

**Issue by ashishhk** [commercetools/commercetools-jvm-sdk#2072]
Issue https://jira.commercetools.com/browse/SUPPORT-10261

Update action SetCustomerGroup is not easy to create because it needs a Referenceable object in its constructor.

http://commercetools.github.io/commercetools-jvm-sdk/apidocs/io/sphere/sdk/customers/commands/updateactions/SetCustomerGroup.html

So if you don't have a customer group to update it is not easy to create a Referenceable object as it has not a constructor,

So library user needs to do a hacky way of implementing an anoynmous class of ResourceImpl like below:

```
return new ResourceImpl<CustomerGroup>(null, null, null, null) {
@Override
public Reference<CustomerGroup> toReference()

{ return Reference.of(CustomerGroup.referenceTypeId(), resourceIdentifier.getId()); }
};
```

So in this case it's better to change the action constructor with
`ResourceIdentifier<CustomerGroup>`, similar to other update actions in the library.

**Comment by ahmetoz** [comment]
I have figured out the same kind of issue is ``io.sphere.sdk.shoppinglists.commands.updateactions##SetCustomer.of`` for the shopping lists.
