### ISSUE TITLE
ShoppingList type should extend withKey and Custom, same applies for the ShoppingListDraft type.

### ISSUE THREAD

**Issue by praveenkumarct** [commercetools/commercetools-jvm-sdk#2073]
Shopping List should extend withKey. Because it has a key.
Here is the link for the Shopping list class.
https://github.com/commercetools/commercetools-jvm-sdk/blob/master/commercetools-models/src/main/java/io/sphere/sdk/shoppinglists/ShoppingList.java

Documentation link below:
https://docs.commercetools.com/api/projects/shoppingLists#shoppinglist

**Comment by ahmetoz** [comment]
Not sure if this is a bug or not, but could be good to have also a ShoppingList and ShoppingListDraft with extending the interfaces (`extends CustomDraft, WithKey`) so library users could follow those interfaces in their generic classes.
