### ISSUE TITLE
Large numbers are not supported by SDK but are supported by platform.

### ISSUE THREAD

**Issue by ashishhk** [commercetools/commercetools-jvm-sdk#2083]
https://jira.commercetools.com/browse/SUPPORT-9654

fix the support bug for JVM SDK.
please check if this also the case for other SDKs.
please check in new generated SDKs as well.

**Comment by jenschude** [comment]
The SDK uses Long e.g for lineitem quantity. This means it already supports the platform range. See 25e74c1f6
