### ISSUE TITLE
Add custom headers when retrieving OAuth Token

### ISSUE THREAD

**Issue by leungkinghin** [commercetools/commercetools-jvm-sdk#2094]
### **Description**
It is an extension of this issue
https://github.com/commercetools/commercetools-jvm-sdk/issues/1691

For normal request, it works properly. Custom header can be injected into request successfully by decorating **SphereClient** in following way :

1. Writing a decorator class
```
public final class CustomHeaderSphereClientDecorator extends SphereClientDecorator {

    private SphereRequestDecorator delegatedSphereRequestDecorator;

    private CustomHeaderSphereClientDecorator(@Nonnull final SphereClient sphereClient) {
        super(sphereClient);
    }

    @Nonnull
    public static SphereClient of(@Nonnull final SphereClient sphereClient) {
        return new CustomHeaderSphereClientDecorator(sphereClient);
    }

    @Override
    public <T> CompletionStage<T> execute(@Nonnull final SphereRequest<T> sphereRequest) {
        delegatedSphereRequestDecorator = new CustomHeaderSphereRequestDecorator<>(sphereRequest);
        return super.execute(delegatedSphereRequestDecorator);
    }

    protected HttpRequestIntent getHttpRequestIntent() {
        return delegatedSphereRequestDecorator.httpRequestIntent();
    }

    private static final class CustomHeaderSphereRequestDecorator<T> extends SphereRequestDecorator<T> {
        CustomHeaderSphereRequestDecorator(@Nonnull final SphereRequest<T> delegate) {
            super(delegate);
        }

        @Override
        public HttpRequestIntent httpRequestIntent() {
            final HttpHeaders headers =
                    HttpHeaders.of(HttpHeaders.USER_AGENT, LIB_NAME + " (ver : " + LIB_VERSION + ")");
            return super.httpRequestIntent().withHeaders(headers);
        }
    }
}
```

2. Decoration of **SphereClient**
```
    public SphereClient getCtpClient() {
        return CustomHeaderSphereClientDecorator.of(ctpClient);
    }
```

However, for OAuth Token request, the request header is created inside **TokenSupplierImpl** during instantiation of **SphereClient**. That means the above decorator doesn't help on OAuth Token request.
https://github.com/commercetools/commercetools-jvm-sdk/blob/2672e60d81d9f8801ac5e195abfff2804ffa45e4/commercetools-java-client-core/src/main/java/io/sphere/sdk/client/TokensSupplierImpl.java#L81

### **Additional Information**
Here we have few considerations :
1. Creating a custom HTTP client in following way to override user-agent doesn't works 100%. 
https://github.com/commercetools/commercetools-jvm-sdk/blob/cfd1b20d40b8a5ecef719470c1637082db284361/commercetools-models/src/test/java/io/sphere/sdk/client/TokensSupplierImplTest.java#L20
It leads to duplicated custom header in request (One is written into user-agent by TokenSupplierImpl, another one is written into HTTP intent by custom decorator above), and marked twice in log file.

2. Also, users can create their own **SphereClient**, which override our provided utility method.
 
Therefore it is suggested to provide another decorator to **SphereClient** so that additional header can be added into OAuth Token request as well, even users adapt their own way to create **SphereClient**.

**Comment by jenschude** [comment]
As a quick suggestion i would implement a custom token supplier with the custom header

**Comment by leungkinghin** [comment]
@jenschude Had a quick look on `TokenSupplierImpl`. We can resolve the duplicated header incident by following similar code snippet in the customised Token Supplier.

> .plus(HttpHeaders.USER_AGENT, UserAgentUtils.obtainUserAgent(httpClient) + "," + syncLibName + "/" + syncLibVersion);



It would be easier to do if `TokenSupplierImpl` class is not finalised in jvm-sdk.

However, the above only applies if customers make use of sync-java utility to create `SphereClient`. If they create their own `SphereClient`, we have no way to control how they initialise Token Supplier.

Let's discuss more details after your holidays. Thank you very much for your suggestion.

**Comment by jenschude** [comment]
Btw as you want to modify the UserAgent. This is what the solutionInfo is for in the [UserAgentUtils](commercetools-java-client-core/src/main/java/io/sphere/sdk/client/UserAgentUtils.java)

It can be set by providing a SolutionInfo class an [META-INF/services/io.sphere.sdk.client.SolutionInfo](commercetools-models/src/test/resources/META-INF/services/io.sphere.sdk.client.SolutionInfo)

**Comment by leungkinghin** [comment]
@jenschude Yes. it is one of solutions.
On the other hand, it brings another concern which people have ever discussed
https://github.com/commercetools/commercetools-jvm-sdk/issues/1691#issuecomment-363083645

That's why we would like to look for alternative to decorate OAuth Token request header.

**Comment by leungkinghin** [comment]
@commercetools/clients-sdk-team  As suggested by Jen couples of weeks ago, we are considering to go on the way of custom token supplier implementation.
Before this, we would like to ask, whether it is feasible to make these classes inheritable, so that jvm-sdk lib user can override them? Thanks.
[RetryableSphereClientBuilder](https://github.com/commercetools/commercetools-jvm-sdk/blob/ef4807f94eee358ea340ce4f3974ff1b37c4861c/commercetools-convenience/src/main/java/io/sphere/sdk/client/retry/RetryableSphereClientBuilder.java), [AutoRefreshSphereAccessTokenSupplierImpl](https://github.com/commercetools/commercetools-jvm-sdk/blob/a5d5b5a37bd7e0e1d34b34d3acd265b47187638e/commercetools-java-client-core/src/main/java/io/sphere/sdk/client/AutoRefreshSphereAccessTokenSupplierImpl.java), [TokensSupplierImpl](https://github.com/commercetools/commercetools-jvm-sdk/blob/0e9c291585ea8088eb0a6614453e1f0311b50021/commercetools-java-client-core/src/main/java/io/sphere/sdk/client/TokensSupplierImpl.java)

**Comment by jenschude** [comment]
The SDK has some Rules in place which check that Impl classes are package only visible and classes that classes are final. Also we could whitelist some classes I would like to avoid this.

But as the TokenSupplier is just an interface one could copy the Impl source and adjust it.

Besides that I opened a [PR](#2136) which allows to specify the additional SolutionInfos to be used for the user agent in the factory methods.
