### ISSUE TITLE
Fix type for assets in AddVariant update action

### ISSUE THREAD

**Issue by jenschude** [commercetools/commercetools-jvm-sdk#2126]
In the AddVariant update action the assets field awaits a `List<Asset>` instead of a `List<AssetDraft>`

https://github.com/commercetools/commercetools-jvm-sdk/issues/1866#issuecomment-797006558

**Comment by praveenkumarct** [comment]
@jenschude  @ashishhk  Thank you for creating a new issue. Can I please know if there is any plan to release the fix for this issue and if yes, any date?

**Comment by ashishhk** [comment]
Hey @praveenkumarct , this is one of our next task in top of the list of JVM SDK Support issues, Should be picked up soon, We don't have a timeline though.

**Comment by praveenkumarct** [comment]
Hello @barbara79, Is it possible to prioritise this issue(bug) and give us the timeline, when can it be released?
