### ISSUE TITLE
Enable updating resources by ID

### ISSUE THREAD

**Issue by ahalberkamp** [commercetools/commercetools-jvm-sdk#2129]
**Situation:**

Currently, the jvm-sdk only supports two ways to create an updatecommand: Creating the command by resource (like: ProductUpdateCommand.of(product))  or
by key (like: ProductUpdateCommand.ofKey(product.getKey(),product.getVersion,updateActions))

**Complication:**

In some cases, we only have the ID of a resource, which have to be updated. So currently we have to fetch the resource by its ID from the ctp and than creating the updateCommand using the fetched resource.
This is inefficient based on that the api offers the possibility to update a resource by its ID

**Resolution:**

Provide a method like `ProductUpdateCommand.ofID(product.getID(),product.getVersion,updateActions))` to enable creating updatecommands based on the resource ids.

**Comment by jenschude** [comment]
You can do this by using the `io.sphere.sdk.models.Versioned.of()` interface method.

Please see also https://commercetools.github.io/commercetools-jvm-sdk/apidocs/io/sphere/sdk/models/Versioned.html

```
But there occasions where you submit ID and version in a form and want to update a resource without fetching it before:

 final String id = "c7b25e66-465f-4b77-8c8b-10f0958a1436";
 final long version = 5;
 final ProductUpdateCommand cmd = ProductUpdateCommand.of(Versioned.of(id, version), Publish.of());
```

**Comment by ahalberkamp** [comment]
Hi @jenschude,
Why doesn`t productprojection still implement the "withKey" interface, even though they provide the "getKey" method?
When this interface would be added to productprojection too, we could simplify our code in the product-sync.

Best regards

Andi
