### ISSUE TITLE
Upgrade from 1.55.0 to 1.62.0

### ISSUE THREAD

**Issue by willianmk** [commercetools/commercetools-jvm-sdk#2131]
Hi,

I checked that there is an update on CT documentation regarding custom field on Address, which is working well. However, the issue I am facing is about the SDK upgrade I placed from the v.1.55.0 to 1.62.0. I am depending on `commercetools-models` module and it did not come.

Basically my current section on Gradle configurations are:

```
dependencies {
    ...
    implementation "com.commercetools.sdk.jvm.core:commercetools-models:$commercetoolsVersion"
    implementation "com.commercetools.sdk.jvm.core:commercetools-java-client-ahc-2_5:$commercetoolsVersion"
    implementation "com.commercetools.sdk.jvm.core:commercetools-convenience:$commercetoolsVersion"
    ....
}
```

Is there anything else I should do in order to have the module on my project properly?

**Comment by jenschude** [comment]
Just forgot to release the staing repository at sonatype. Should be available in some minutes now.
