### ISSUE TITLE
Vulnerable dependencies have been scanned

### ISSUE THREAD

**Issue by leungkinghin** [commercetools/commercetools-jvm-sdk#2137]
### Description
When we scan our application by Snyk CLI, several dependencies introduced in JVM-SDK are reported as vulnerable regarding to security.

### Suggestion
Please check if it is possible to upgrade the corresponding dependencies, so that the security risks can be resolved.

### Additional Info
**io.netty**
https://app.snyk.io/vuln/SNYK-JAVA-IONETTY-543490
Suggested to upgrade to version 4.1.44.Final or higher

**commons.io**
https://app.snyk.io/vuln/SNYK-JAVA-COMMONSIO-1277109
Suggested to upgrade to version 2.7 or higher

**com.fasterxml.jackson.dataformat**
https://app.snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONDATAFORMAT-1047329
Suggested to upgrade to version 2.11.4, 2.12.1 or higher

**Comment by butenkor** [comment]
Hi @ashishhk Is there any timeline for this issue?

**Comment by jenschude** [comment]
The v2.0.0 release updated the vulnerable dependencies to more recent ones
