### ISSUE TITLE
Custom correlation id in CT requests

### ISSUE THREAD

**Issue by KateMRogers** [commercetools/commercetools-jvm-sdk#2162]
Hello guys,

For my project in each request to our backend service we get a request id. This request id should be propagated as a correlation id header to CT. 

The problem is that I do not find any straightforward way of doing it.
So far I've tried the following:
1. Use SphereClientDecorator which would add my custom value to the request header.

 It doesn't fit because: The SphereClientImpl class adds it's own correlation id to the same header.

<img width="680" alt="image" src="https://user-images.githubusercontent.com/79314258/123093387-4d960f80-d434-11eb-9d12-8b64a0c3abbb.png">

 As a result I have two ids in the X-Correlation-ID header, and I need only one, which should be my custom one.

2. Leverage the extension point on the SphereClientConfigBuilder level

<img width="254" alt="image" src="https://user-images.githubusercontent.com/79314258/123093782-c09f8600-d434-11eb-87db-3db3f520ce51.png">

 It doesn't fit because: The CorrelationIdGenerator interface is not public. 

The way I see it working: ideally, CorrelationIdGenerator should be public so that it could be extended, or as an alternative, get rid of this interface and use supplier instead.

Am I missing the obvious?

Thanks in advance

**Comment by jenschude** [comment]
Atm only the SphereClientImpl has a factory method to inject a CorrelationIdGenerator. Adding a decorator will not help as the SphereClientImpl will always add it's own correlation id header.

But it may be possible to expose the factory method to the SphereClient/Factory to enable custom generators

**Comment by KateMRogers** [comment]
Yeah, I see, I was a bit confused because I saw correlationIdGenerator field on the SphereClientConfig level.
Anyway, the idea with a public factory method on SphereClient/Factory would work perfectly

**Comment by KateMRogers** [comment]
Awesome, thanks. Also, I think we need the CorrelationIdGenerator interface to be public, otherwise I am not able to provide custom imps
