### ISSUE TITLE
AttributeAccess for "nested set" attributes messes items order

### ISSUE THREAD

**Issue by kirmerzlikin** [commercetools/commercetools-jvm-sdk#2169]
**Describe the bug**
When saving or retrieving "nested set" attribute using `AttributeAccess.ofNestedSet()`, the order of items gets lost.
It happens because [`NestedSetAttributeMapperImpl`](https://github.com/commercetools/commercetools-jvm-sdk/blob/master/commercetools-models/src/main/java/io/sphere/sdk/products/attributes/NestedSetAttributeMapperImpl.java), used by this attribute access for serialization and deserialization, [transforms `AttributeContainer`s into `List<Attribute>`s](https://github.com/commercetools/commercetools-jvm-sdk/blob/master/commercetools-models/src/main/java/io/sphere/sdk/products/attributes/NestedSetAttributeMapperImpl.java#L32) (and [vice versa](https://github.com/commercetools/commercetools-jvm-sdk/blob/master/commercetools-models/src/main/java/io/sphere/sdk/products/attributes/NestedSetAttributeMapperImpl.java#L24)) using stream collector `toSet()` which does not preserve items order. 

**To Reproduce**
```java
    @Test
    public void saving() {
        LinkedHashSet<AttributeContainer> orderedItems = new LinkedHashSet<>();
        orderedItems.add(AttributeContainer.of(singletonList(Attribute.of("foo", IntNode.valueOf(42)))));
        orderedItems.add(AttributeContainer.of(singletonList(Attribute.of("foo", IntNode.valueOf(43)))));
        orderedItems.add(AttributeContainer.of(singletonList(Attribute.of("foo", IntNode.valueOf(44)))));

        AttributeDraft nestedSetAttributeDraft = 
             AttributeDraft.of("nested-set-attribute", AttributeAccess.ofNestedSet(), orderedItems);
        String nestedSetAttributeJson = SphereJsonUtils.toJsonString(nestedSetAttributeDraft.getValue());

        assertEquals(
                "[[{\"name\":\"foo\",\"value\":42}],[{\"name\":\"foo\",\"value\":43}],[{\"name\":\"foo\",\"value\":44}]]",
                nestedSetAttributeJson);
    }

    @Test
    public void retrieving() {
        JsonNode nestedSetAttributeJson =
                SphereJsonUtils.parse("[[{\"name\":\"foo\",\"value\":42}],[{\"name\":\"foo\",\"value\":43}],[{\"name\":\"foo\",\"value\":44}]]");
        Attribute nestedSetAttribute = Attribute.of("nested-set-attribute", nestedSetAttributeJson);

        Set<AttributeContainer> setItems = nestedSetAttribute.getValue(AttributeAccess.ofNestedSet());
        Iterator<AttributeContainer> setItemsIterator = setItems.iterator();

        assertEquals(42,
                setItemsIterator.next().getAttribute("foo").getValue(AttributeAccess.ofInteger()));
        assertEquals(43,
                setItemsIterator.next().getAttribute("foo").getValue(AttributeAccess.ofInteger()));
        assertEquals(44,
                setItemsIterator.next().getAttribute("foo").getValue(AttributeAccess.ofInteger()));
    }
```

**Expected behavior**
If items are ordered when "nested set" attribute is saved, that order should be preserved.

**Stack information (please complete the following information):**
 - Java: 11
 - SDK: 1.64.0

**Comment by jenschude** [comment]
I just committed the fix for the issue. Will be available with the next release

Thanks for the report
