### ISSUE TITLE
Retry delegate or auto retry for client

### ISSUE THREAD

**Issue by schleichardt** [commercetools/commercetools-jvm-sdk#260]
If the SPHERE.API is not available (503) retry again.

@lauraluiz Should the client automatically retry requests or should it be composable via decorator pattern?

**Comment by sam0r** [comment]
I personally would go for a compose-able solution if it gives me more options on what to do if I need to perform a retry.

**Comment by schleichardt** [comment]
I also prefer this, since an included behavior is not obvious and works bad for fail fast approaches.

**Comment by lauraluiz** [comment]
I agree, we should not decide anything for the developer. But some help for this common situation is in order.

**Comment by Niondir** [comment]
It should be somehow configurable for the Dev. For a retry mechanism it should be fine to have a set of settings for the SphereClient.

**Comment by schleichardt** [comment]
duplicate https://github.com/sphereio/sphere-jvm-sdk/issues/361

**Comment by schleichardt** [comment]
I close it since it is a duplicate and already implemented
