### ISSUE TITLE
Add helper to generate unique orderNumbers/customerNumbers

### ISSUE THREAD

**Issue by hajoeichler** [commercetools/commercetools-jvm-sdk#32]
In order to avoid duplicates in order numbers (or customer numbers), it would be nice to get a helper that generates a project-wide unique number.

**Comment by schleichardt** [comment]
see also https://github.com/sphereio/dev.commercetools.com/issues/61

@lauraluiz You write the implementation and I write the spec/tests? :grinning:

**Comment by lauraluiz** [comment]
:+1: but is it going to be in the JVM SDK?

**Comment by schleichardt** [comment]
Yes, in the module sphere-convenience.
