### ISSUE TITLE
use types/methods to show if count for variants or product in facets

### ISSUE THREAD

**Issue by schleichardt** [commercetools/commercetools-jvm-sdk#353]

**Comment by lauraluiz** [comment]
The idea is nice for sure, I just have to do a bit of research in that topic to see if is really feasible.

**Comment by schleichardt** [comment]
Should we include this in 1.0.0?

**Comment by lauraluiz** [comment]
If that means this week, no, I don't think so. But since it is an experimental class, we have some flexibility to introduce these changes later.

**Comment by lauraluiz** [comment]
If that means in a month, then hopefully I will :P

**Comment by schleichardt** [comment]
Not necessary, what is counted can be specified: https://docs.commercetools.com/http-api-projects-products-search.html#counting-products
