### ISSUE TITLE
commercetools platform rebranding

### ISSUE THREAD

**Issue by schleichardt** [commercetools/commercetools-jvm-sdk#626]
* move this GitHub repo (Hajo/ops will take carr)
* move Scala addons GitHub repo  (Hajo/ops will take car)
* move Java experimantal GitHub repo  (Hajo/ops will take care)
* [x] adjust Java packages in this repo (we keep the old ones)
* [x] adjust Java packages in Scala addons repo (we keep the old ones)
* [x] adjust Java packages in Java experimantal repo (we keep the old ones)
* [x] rename sphere classes in this repo  (we keep the old ones)
* [x] adjust groupId and artifactId in all 3 repos
* [ ] mention rebranding in README

**Comment by schleichardt** [comment]
@hajoeichler 

The SDK is then called commercetools-jvm-sdk?
And the package for the Java code is `io.commercetools.sdk`?
And we release under Maven Central groupId `io.commercetools.sdk.jvm`? Then we need to ask at sonatype for rights for the `io.commercetools` organization.

**Comment by schleichardt** [comment]
@mmoelli This is a blocker for the RC1 release.

**Comment by mmoelli** [comment]
@nkuehn please have a look.

**Comment by nkuehn** [comment]
@schleichardt  @hajoeichler  
  * we should ask sonatype for io.commercetools anyways to have that assured independently of whether we use it now or not or later 
 * package and group look OK
 * don't forget the modules 

so far it's easy to migrate client code. The really evil part for user code is changing all the "Sphere" prefixed Classes, field names etc.  "SphereLogger" etc.
e.g. will "SphereLogger" become a "CommercetoolsLogger" (very long)  or a "CtLogger" or whatever?

**Comment by schleichardt** [comment]
We keep the sphere name spaces for the classes so it won't be a breaking change for the rebranding.

**Comment by schleichardt** [comment]
group id: com.commercetools.sdk.jvm.core
artifact ids: commercetools-models, commercetools-default-java-client (currently async http client 2.0), commercetools-convenience
