### ISSUE TITLE
 SerializationFeature.FAIL_ON_EMPTY_BEANS

### ISSUE THREAD

**Issue by schleichardt** [commercetools/commercetools-jvm-sdk#715]
@yanns @lauraluiz Is it a bad idea to DEACTIVATE this feature in our JsonUtil?

**Comment by yanns** [comment]
what are the repercussions for this change? Do you have an example of such an error with the current SDK.

**Comment by schleichardt** [comment]
Sometime I need a class hierarchy for a new feature but do not fill a class with properties. When I have such a bean then the Jackson mapper complains.

**Comment by yanns** [comment]
OK, thx for the explanation.

I've personally never used this feature.
I am afraid I cannot give you any more information about it.

**Comment by lauraluiz** [comment]
I also have no experience with that, but from what I know it is a measure to inform you about potential problems in your code, so nothing to be broken but we will lose some information. Nonetheless, as long as the IT are covering the usage of all classes meant to be deserialized, it should be safe.

**Comment by schleichardt** [comment]
seems like I won't activate this
