### ISSUE TITLE
CartDraft usability improvements

### ISSUE THREAD

**Issue by schleichardt** [commercetools/commercetools-jvm-sdk#816]
@lauraluiz should we provide not type-safe helpers like those:

``` java
final CartDraft cartDraft = CartDraft.of("EUR").withCountry("DE");
```

or do we just allow

``` java
CurrencyUnit currencyUnit = Monetary.getCurrency("EUR");
CountryCode currencyCode = CountryCode.getByCode("DE");
final CartDraft cartDraft = CartDraft.of(currencyUnit).withCountry(currencyCode);
```

?

**Comment by lauraluiz** [comment]
I guess it would be just syntactic sugar of the latter? In a big project you would store the CurrencyCode and CurrencyUnit somewhere, so you would not use it. But for tests and small projects is convenient, I'd say. But if we introduce it here, I would say it should be introduced anywhere else (where a CurrencyUnit or CountryCode is accepted) for consistency. Then it can become too much code noise.

**Comment by schleichardt** [comment]
I am not sure if this is a 'yes' or a 'no'.

**Comment by katmatt** [comment]
I agree with @lauraluiz and I adding it everywhere does only make sense for our tests. For our users it wouldn't provide a lot of value.
