### ISSUE TITLE
test gzip packaged body

### ISSUE THREAD

**Issue by schleichardt** [commercetools/commercetools-jvm-sdk#890]

**Comment by katmatt** [comment]
@ccsalazarr-commercetools A HTTP Client can request a gzipped response by setting the HTTP Header `Accept-Encoding` to `gzip`. But I don't know how a user of our SDK could set this header. Additionally it would also be nice to run one (or all) of our integration tests with gzip enabled.

**Comment by lauraluiz** [comment]
The header is always set https://github.com/commercetools/commercetools-jvm-sdk/blob/master/commercetools-java-client-core/src/main/java/io/sphere/sdk/client/SphereClientImpl.java#L113, you cannot modify it (to be fair you could from the HTTP client, but that's offtopic).

What was missing here is simply to test that it's actually being gzipped (that's what I understand at least).

**Comment by katmatt** [comment]
It works correctly.
