### ISSUE TITLE
Document ConcurrentModificationException concerning manual conflict resolving

### ISSUE THREAD

**Issue by schleichardt** [commercetools/commercetools-jvm-sdk#954]
@lauraluiz do you have an idea what we can present how to solve a 409 issue with just getting the new version and updating it?

**Comment by lauraluiz** [comment]
Do you mean a particular use case?

**Comment by schleichardt** [comment]
no

**Comment by schleichardt** [comment]
see http://commercetools.github.io/commercetools-jvm-sdk/apidocs/io/sphere/sdk/client/ConcurrentModificationException.html
