### ISSUE TITLE
CustomerSignInResultExpansionModel with cart possible?

### ISSUE THREAD

**Issue by schleichardt** [commercetools/commercetools-jvm-sdk#955]

**Comment by katmatt** [comment]
We have to add the method `CartExpansionModel<T> cart();`
to the `CustomerSignInResultExpansionModel` interface and implement it in `CustomerSignInResultExpansionModelImpl`.

And then we can test it with an integration test. If it fails, it's not supported by our backend.

**Comment by ccsalazarr-commercetools** [comment]
CustomerSignInResultExpansionModel with cart is possible
