### ISSUE TITLE
Automate release process

### ISSUE THREAD

**Issue by schleichardt** [commercetools/commercetools-jvm-sdk#96]
We should automate our release so that every developer can perform a release without having to install the required credentials on his local machine.

**Comment by katmatt** [comment]
We already created shell scripts to prepare a release and a job on our CI server to build a release. We"re now wanting for our OPS team to enable our CI job to access the required key for signing our release jar files.

**Comment by katmatt** [comment]
We now have an automated release build on our internal integration server 😄

**Comment by schleichardt** [comment]
👏
